django_myical/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render, HttpResponseRedirect
from django.urls import path, reverse
from django.utils import translation
from django.utils.translation import check_for_language, get_language

from mycalendar.forms import MyCalendarForm
from mycalendar.models import MyCalendar


def set_lang(request):
    response = None
    if 'lang' in request.GET and check_for_language(request.GET.get('lang')):
        user_language = request.GET.get('lang')
        translation.activate(user_language)
        if 'next' in request.GET:
            response = HttpResponseRedirect(request.GET.get('next'))
        else:
            response = HttpResponseRedirect(reverse('home'))
        response.set_cookie(
            settings.LANGUAGE_COOKIE_NAME,
            user_language,
            max_age=settings.LANGUAGE_COOKIE_AGE,
            path=settings.LANGUAGE_COOKIE_PATH,
            domain=settings.LANGUAGE_COOKIE_DOMAIN,
            secure=settings.LANGUAGE_COOKIE_SECURE,
            httponly=settings.LANGUAGE_COOKIE_HTTPONLY,
            samesite=settings.LANGUAGE_COOKIE_SAMESITE,
        )
    return response


def home(request):
    c = {}
    if request.method == 'POST':
        form = MyCalendarForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save()
            instance.save()
            instance.get_ics()
        c['form'] = MyCalendarForm()
    else:
        c['form'] = MyCalendarForm()
    c['object_list'] = MyCalendar.objects.all().order_by('-pk')[:5]
    return render(request, "model_form_upload.html", c)


urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('lang/', set_lang, name='lang'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mycalendar/models.py
import hashlib
from datetime import datetime, timedelta
from urllib.parse import quote_plus
from django.conf import settings
import pytz
#from django.core.files import File, ContentFile
from django.core.files.base import ContentFile
from django.db import models
from django.utils.translation import gettext as _
from icalendar import Calendar, Event, vText
#from django.contrib.sites.models import get_current_site


class MyCalendar(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("Name"), )
    document = models.FileField(upload_to='documents/')
    ics = models.FileField(upload_to='ics/', blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_ics(self):
        ret = True
        try:
            cal = Calendar()
            calname = '%s' % (self.name)
            cal.add('prodid', '-// %s //' % (calname))
            cal.add('version', '2.0')
            cal.add('X-WR-CALNAME', '%s' % calname)
            fichier = open(self.document.path, 'r', encoding='latin-1' )
            for line in fichier.readlines():
                vec = line.split(';')
                if len(vec) >= 3:
                    if '/' in vec[0]:
                        date = vec[0].split('/')
                        day = date[0]
                        month = date[1]
                        year = date[2]
                    elif "-" in vec[0]:
                        date = vec[0].split(':')
                        day = date[2]
                        month = date[1]
                        year = date[0]
                    else:
                        print("error date")
                    if '.' in vec[1]:
                        hour, minute = vec[1].split('.')
                    elif ':' in vec[1]:
                        hour, minute = vec[1].split(':')
                    event = Event()
                    match = ('%s' % vec[2]) if len(vec[3]) < 2 else ('%s-%s' % (vec[2], vec[3]))
                    event.add('summary', match)
                    date_start = datetime(int(year), int(month), int(day), int(hour), int(minute), 0,
                                          tzinfo=pytz.timezone('Europe/Brussels'))
                    event.add('dtstart', date_start)
                    event.add('dtend', date_start + timedelta(hours=1, minutes=30))
                    event.add('dtstamp', datetime.now())
                    if len(vec) > 4:
                        adr = vec[4][:-1]
                        if len(adr) > 5:
                            event['location'] = vText(adr)
                    event['uid'] = hashlib.sha224(("%s%s" % (vec[0], match)).encode('utf-8')).hexdigest()
                    cal.add_component(event)
            path_ics = '%s.ics' % calname.replace(' ', '_')
            #f = open(path_ics, 'wb')
            #f.write(cal.to_ical())
            #f.close()
            #f = open(path_ics, 'r')
            #self.ics.save(path_ics, File(f))
            #f.close()
            self.ics.save(path_ics, ContentFile(cal.to_ical()))
        except:
            print("error")
            ret = False
        return ret

    def get_ics_full_url(self):
        full_url = "http://%s%s" % ( settings.WEBSITE, self.ics.url)
        return full_url
    
    def get_ics_facebook_link(self):
        url = "https://www.facebook.com/sharer/sharer.php?u=%s" % quote_plus(self.get_ics_full_url())
        return url

    # <button class="btn btn-social-icon btn-facebook" type="button" onclick="dpisocial_share_this('https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.lesoir.be%2F321090%2Farticle%2F2020-08-26%2Fen-aout-une-personne-contaminee-sur-5-avait-voyage-selon-le-centre-de-crise', 'facebook', 321090);"><i class="fa fa-facebook icon icon-facebook"></i></button>

    def get_ics_twitter_link(self):
        url = "https://twitter.com/intent/tweet?text=%s&url=h%s&via=rapid_api" % (self.name, quote_plus(self.ics.url))
        return url

    def get_ics_mail_link(self):
        url = "mailto:?subject=Calendar %s&body=Link to the calendar : %s " % (self.name, quote_plus(self.ics.url))
        return url

    # <button onclick="location.href='mailto:?subject=Un%20article%20int%C3%A9ressant%20%C3%A0%20lire%20sur%20Le%20Soir%20Plus&amp;body=Un%20article%20int%C3%A9ressant%20%C3%A0%20lire%20https%3A%2F%2Fwww.lesoir.be%2F321090%2Farticle%2F2020-08-26%2Fen-aout-une-personne-contaminee-sur-5-avait-voyage-selon-le-centre-de-crise'" class="btn btn-social-icon btn-mail" type="button"><i class="fa fa-envelope-o"></i><span class="label"></span></button>

    def get_ics_whatsapp_link(self):
        url = "https://api.whatsapp.com/send?text=Link to the calendar '%s' : %s " % (
        self.name, quote_plus(self.ics.url))
        return url

    # <button class="btn btn-social-icon btn-whatsapp" type="button" onclick="dpisocial_share_this('https://api.whatsapp.com/send?text=Voici un article intéressant - https://www.lesoir.be/321090/article/2020-08-26/en-aout-une-personne-contaminee-sur-5-avait-voyage-selon-le-centre-de-crise', 'whatsapp', 321090);"><i class="fa fa-whatsapp icon icon-whatsapp"></i></button>

    def get_ics_messenger_link(self):
        return None
    # <button class="btn btn-social-icon btn-messenger" type="button" onclick="dpisocial_share_messenger('https://www.lesoir.be/321090/article/2020-08-26/en-aout-une-personne-contaminee-sur-5-avait-voyage-selon-le-centre-de-crise', 'facebook', '321090');"><i class="fa fa-facebook icon icon-messenger"></i></button>

mycalendar/forms.py
from django import forms
from mycalendar.models import MyCalendar


class MyCalendarForm(forms.ModelForm):
    class Meta:
        model = MyCalendar
        fields = ('name', 'document', )

mycalendar/views.py
from django.shortcuts import render

# Create your views here.

templates/_header.html
{% load static i18n common_tags %}
<header style="border-bottom: 1px solid #eee;">
    <!-- End Messages -->
    <div class="px-2 bg-dark">
        <!-- Navbar -->
        <!-- Important: columns can be used directly in navbar since it is d-flex -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark p-0 py-2">
            <a class="navbar-brand" href="/">django-ical</a>
            <button aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
                    data-target="#navbarCollapse" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                </ul>
                <ul class="navbar-nav navbar-right">
                    <li>
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        <div class="btn-toolbar" role="toolbar">

                            <div class="btn-group mr-2" role="group">
                                {% for language in languages %}
                                <a class="btn btn-secondary {% if language.code == LANGUAGE_CODE %}active{% endif %}"
                                   href="/lang/?lang={{language.code}}&next={{ request.get_full_path }}">{{ language.code | upper }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- End Navbar -->
    </div>
    <!-- Messages -->
    <div>
        {% if messages %}
        {% for message in messages %}
        <div %} %} class="alert alert-icon alert-{{ message.tags }} alert-dismissible fade show mb-0" endif if
             message.tags role="alert" style="border-radius:0;" {%
             {%>
            {{ message }}
            <button aria-label="Close" class="close" data-dismiss="alert" type="button">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</header>

templates/base.html
{% load static i18n common_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" name="viewport">
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.css' rel="stylesheet" type="text/css"/>
    <link href='https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.1/css/all.css' rel="stylesheet"
          type="text/css">
    <link href="{% static 'fileupload/css/file-upload.css' %}" rel="stylesheet" type="text/css"/>

    <style media="screen">
            body {
                display: flex;
                flex-direction: column;
                min-height: 100vh;
            }
            .btn-socialm{
                border-radius: 20px;
                border: none;
                height: 32px;
                line-height: 32px;
                padding: 0 8px;
                width:32px;
            }

    </style>
    <title>django-ical</title>
</head>
<body>
{% include "_header.html" %}
{% if DEBUG %}
<div class="box">
    <div class="ribbon ribbon-top-left"><span>{{STATE}}</span></div>
    {% endif %}
    {% block content %}{% endblock content %}
    {% if DEBUG %}
</div>
{% endif %}
<script crossorigin="anonymous" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"
        src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
{% block extrascripts %}{% endblock extrascripts %}
</body>
</html>

templates/model_form_upload.html
{% extends 'base.html' %}
{% load widget_tweaks  static i18n common_tags %}

{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-sm-6 mb-4">
            <div class="card">
                <div class="card-header">
                    <h3 class="float-left mb-0">Form</h3>
                </div>
                <div class="card-body">
                    <form enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <input class="form-control" id="id_name" maxlength="100" name="name" placeholder="Name"
                                   required="true" type="text">
                            <div class="">

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="file-upload btn btn-success" for="id_document">Select a valid CSV file
                                <input class="form-control" id="id_document" name="document" placeholder="Document"
                                       required="true" type="file"></label>
                        </div>
                        <button class="submit-btn btn btn-primary" type="submit">Generate ical</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-6  mb-4">
            <div class="card">
                <div class="card-header">
                    <h3 class="float-left mb-0">output</h3>
                </div>
                <div class="card-body">
                    {% for object in object_list %}
                    <div class="row justify-content-between">
                        <div>
                            <a class="float-left" href="{{ object.document.url }}">{{object}}</a>
                        </div>
                        <div class="float-right">
                            {% if object.ics %}
                            <a class="btn btn-socialm" href="{{object.get_ics_facebook_link}}"
                               style="background-color: #4267B2"><i class="fab fa-facebook-f"
                                                                    style="color:white"></i></a>
                            <!--<a class="btn btn-socialm" href="{{object.get_ics_messenger_link}}"
                               style="background-color: #448AFF"><i class="fab fa-facebook-messenger"
                                                                    style="color:white"></i></a>-->
                            <a class="btn btn-socialm" href="{{object.get_ics_twitter_link}}"
                               style="background-color: #55acee"><i class="fab fa-twitter" style="color: white"></i></a>
                            <a class="btn btn-socialm" href="{{object.get_ics_whatsapp_link}}"
                               style="background-color:#25d366"><i
                                    class="fab fa-whatsapp" style="color:white"></i></a>
                            <a class="btn btn-socialm" href="{{object.get_ics_mail_link}}"
                               style="background-color: grey"><i class="fas fa-envelope" style="color:white"></i></a>
                            <a class="btn btn-socialm copy" data-placement="top" data-toggle="tooltip"
                               data-url="{{object.get_ics_full_url}}" href="#"
                               style="background-color:black"
                               title="copy to url the link of the ics file"><i
                                    class="far fa-clone" style="color:white"></i></a>
                            <a class="btn btn-socialm" data-placement="top" href="{{ object.ics.url }}"
                               style="background-color:black"
                               title="download the ics file"><i class="fas fa-download" style="color:white"></i></a>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 mb-4">
            <div class="card">
                <div class="card-header">
                    <h3 class="float-left mb-0">Tutorial</h3>
                </div>
                <div class="card-body">
                    <p>Give a name and a valid csv file</p>
                    <p>Format of csv file : <code>Date;Hour;Subject;detail;Address;</code></p>
                    <p>For sport calendar : <code>Date;Hour;Team Home;Team Away;Address;</code></p>
                    <p>Example : <code>31/12/2021;21.30;RBP;SCC;Avenue Des Vaillants 2 1200 Woluwé-St-Lambert;</code>
                    </p>
                    <p>Format for date : <code>dd/mm/yyyy</code> or <code>yyyy-mm-dd</code></p>
                    <p>Format for hour : <code>hh:mm</code> or <code>hh.mm</code></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extrascripts %}
<script src="{% static '/fileupload/js/file-upload.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('.file-upload').file_upload();

        $('.copy').on('click', function(){
            var dummy = document.createElement("input");
            //dummy.setAttribute("type", "hidden");
            dummy.setAttribute("id", "dummy_id");
            document.body.appendChild(dummy);
            document.getElementById("dummy_id").value=$(this).data('url');
            dummy.select();
            dummy.setSelectionRange(0, 99999);
            document.execCommand("copy");
            document.body.removeChild(dummy);
        });
    });

</script>
{% endblock extrascripts %}